import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Eyebrow, PageHero } from "@/components/page-ui";
export const Route=createFileRoute("/contact")({validateSearch:(s:Record<string,unknown>)=>({product:typeof s["product"]==="string"?s["product"]:undefined}),head:()=>({meta:[{title:"Contact | Pawan Agri Exports"},{name:"description",content:"Contact Pawan Agri Exports in Ahmedabad for bulk product sourcing, specifications, packaging, and export enquiries."},{property:"og:title",content:"Contact Pawan Agri Exports"},{property:"og:description",content:"Discuss your bulk sourcing and export requirement with our trade desk."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Contact});
function Contact(){const {product}=Route.useSearch();const [sent,setSent]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const subject=`Export enquiry${f.get("product")?` — ${f.get("product")}`:""}`;const body=`Name: ${f.get("name")}\nCompany: ${f.get("company")}\nEmail: ${f.get("email")}\nPhone: ${f.get("phone")}\nProduct: ${f.get("product")}\n\nRequirement:\n${f.get("message")}`;setSent(true);window.location.href=`mailto:info@pawanagriexports.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}return <><PageHero eyebrow="Get in touch" title="Tell us what you need to source." copy="Share your product, grade, quantity, packaging, and destination. Our trade desk will help shape the right supply solution."/><section className="section"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><Eyebrow>Corporate office & enquiries</Eyebrow><h2 className="mt-4 text-3xl font-semibold">Pawan Agri Exports</h2><div className="mt-8 grid gap-4"><a className="contact-row" href="tel:+918128200663"><Phone/><span><small>Phone / WhatsApp</small>+91 81282 00663</span></a><a className="contact-row" href="mailto:info@pawanagriexports.com"><Mail/><span><small>Email</small>info@pawanagriexports.com</span></a><a className="contact-row" href="https://wa.me/918128200663" target="_blank" rel="noreferrer"><MessageCircle/><span><small>Quick enquiry</small>Chat on WhatsApp</span></a><div className="contact-row"><MapPin/><span><small>Office</small>Ahmedabad, Gujarat 380061, India</span></div></div></div><form className="border border-border bg-secondary p-6 md:p-9" onSubmit={submit}><h2 className="text-2xl font-semibold">Send a trade enquiry</h2><p className="mt-2 text-sm text-muted-foreground">Your email app will open with these details ready to send.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="field">Name *<Input name="name" required placeholder="Your name"/></label><label className="field">Company<Input name="company" placeholder="Company name"/></label><label className="field">Email *<Input name="email" type="email" required placeholder="you@company.com"/></label>
<label className="field">Phone / WhatsApp<Input name="phone" type="tel" placeholder="Country code + number"/></label><label className="field sm:col-span-2">Product or service<Input name="product" defaultValue={product} placeholder="e.g. Cumin Seeds, 25 kg bags"/></label><label className="field sm:col-span-2">Requirement *<Textarea name="message" required rows={6} placeholder="Quantity, grade, packaging, destination, and timeline"/></label></div><Button size="lg" className="mt-6" type="submit">Prepare email <ArrowRight/></Button>{sent&&<p className="mt-4 text-sm font-medium text-primary">Your email app should now be open.</p>}</form></div></section></>}