import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PageHero, ProductCard, QuoteBand } from "@/components/page-ui";
import { products } from "@/lib/catalog";

export const Route=createFileRoute("/products/")({head:()=>({meta:[{title:"Products | Pawan Agri Exports"},{name:"description",content:"Browse cumin, coriander, fennel, fenugreek, psyllium, vanilla, cinnamon, avocado, henna and groundnuts for export."},{property:"og:title",content:"Export Product Range | Pawan Agri Exports"},{property:"og:description",content:"Premium spices, botanicals, fresh produce, and nuts for international markets."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Products});
function Products(){const [query,setQuery]=useState("");const [category,setCategory]=useState("All");const categories=["All",...new Set(products.map(p=>p.category))];const shown=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.origin}`.toLowerCase().includes(query.toLowerCase())),[query,category]);return <><PageHero eyebrow="Product catalogue" title="Ingredients selected for performance." copy="Explore our current sourcing range. Specifications and grades can be aligned with your market and application requirements."/><section className="section"><div className="site-container"><div className="flex flex-col gap-5 border-b border-border pb-7 md:flex-row md:items-center md:justify-between"><div className="relative w-full md:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products or origin" className="h-11 pl-10"/></div><div className="flex flex-wrap gap-2" aria-label="Product categories">{categories.map(c=><Button key={c} size="sm" variant={category===c?"default":"outline"} onClick={()=>setCategory(c)}>{c}</Button>)}</div></div><p className="mt-7 text-sm text-muted-foreground">Showing {shown.length} products</p><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{shown.map(p=><ProductCard key={p.slug} product={p}/>)}</div>{shown.length===0&&<div className="py-24 text-center"><h2 className="text-2xl font-semibold">No products found</h2><p className="mt-2 text-muted-foreground">Try another name or category.</p></div>}</div></section><QuoteBand/></>}